name: Deploy Frontend to GCP

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Deploy to GCS bucket
      run: |
        # Sync the build files to the bucket
        gsutil -m rsync -r -d dist/ gs://${{ secrets.GCP_BUCKET_NAME }}/
        
        # Set proper content types
        gsutil -m setmeta -h "Content-Type:text/html" -h "Cache-Control:no-cache" gs://${{ secrets.GCP_BUCKET_NAME }}/index.html
        gsutil -m setmeta -h "Content-Type:text/css" gs://${{ secrets.GCP_BUCKET_NAME }}/**/*.css
        gsutil -m setmeta -h "Content-Type:application/javascript" gs://${{ secrets.GCP_BUCKET_NAME }}/**/*.js
        
        echo "🚀 Deployment completed successfully!"
        echo "🌐 Website URL: https://storage.googleapis.com/${{ secrets.GCP_BUCKET_NAME }}/index.html"